-- List of transformers from http://tfarchive.com/community/showthread.php?t=49947
INSERT into transformers values(0, "Hightail");
INSERT into transformers values(1, "Junkyard");
INSERT into transformers values(2, "Cutter");
INSERT into transformers values(3, "Umbra");
INSERT into transformers values(4, "Midnighter XR4");
INSERT into transformers values(5, "Artfire");
INSERT into transformers values(6, "Strafe");
INSERT into transformers values(7, "Night");
INSERT into transformers values(8, "Sky Garry");
INSERT into transformers values(9, "Afterburner");
INSERT into transformers values(10, "Raindance");
INSERT into transformers values(11, "Scowl");
INSERT into transformers values(12, "Scattorshot");
INSERT into transformers values(13, "Nightscream");
INSERT into transformers values(14, "Killzone");
INSERT into transformers values(15, "Black Heat");
INSERT into transformers values(16, "Breakdown");
INSERT into transformers values(17, "Growl");
INSERT into transformers values(18, "Rattletrap");
INSERT into transformers values(19, "Noctorro");
INSERT into transformers values(20, "Scrap Iron");
INSERT into transformers values(21, "Killer Punch");
INSERT into transformers values(22, "CraGun");
INSERT into transformers values(23, "Sundor");
INSERT into transformers values(24, "Blackarachnia");
INSERT into transformers values(25, "Storm Jet");
INSERT into transformers values(26, "TopHeavy");
INSERT into transformers values(27, "Eject");
INSERT into transformers values(28, "Twitcher F451");
INSERT into transformers values(29, "Processor");
INSERT into transformers values(30, "Alan");
INSERT into transformers values(31, "Freed");
INSERT into transformers values(32, "Sky Blast");
INSERT into transformers values(33, "Rewind");
INSERT into transformers values(34, "Servo");
INSERT into transformers values(35, "Scrounge");
INSERT into transformers values(36, "Bigmos");
INSERT into transformers values(37, "Victory Leo");
INSERT into transformers values(38, "Flanker");
INSERT into transformers values(39, "Airraptor");
INSERT into transformers values(40, "Gamma Supreme");
INSERT into transformers values(41, "Groundspike");
INSERT into transformers values(42, "Ultra Magnus");
INSERT into transformers values(43, "Nebulon");
INSERT into transformers values(44, "Yukikaze");
INSERT into transformers values(45, "Crosshairs");
INSERT into transformers values(46, "Brawl");
INSERT into transformers values(47, "Megadeath");
INSERT into transformers values(48, "Sigma Supreme");
INSERT into transformers values(49, "Scissor Boy");
INSERT into transformers values(50, "Skram");
INSERT into transformers values(51, "Blurr");
INSERT into transformers values(52, "Blaster");
INSERT into transformers values(53, "Skullcruncher");
INSERT into transformers values(54, "Autostinger");
INSERT into transformers values(55, "Turbo Master");
INSERT into transformers values(56, "Hydra");
INSERT into transformers values(57, "Torca");
INSERT into transformers values(58, "Loafer");
INSERT into transformers values(59, "Zigzag");
INSERT into transformers values(60, "CementHead");
INSERT into transformers values(61, "Packrat");
INSERT into transformers values(62, "Shuffer");
INSERT into transformers values(63, "Tasmania Kid");
INSERT into transformers values(64, "Sludge");
INSERT into transformers values(65, "Sixknight");
INSERT into transformers values(66, "Camshaft");
INSERT into transformers values(67, "Omega Spreem");
INSERT into transformers values(68, "Gulf");
INSERT into transformers values(69, "Gearhead");
INSERT into transformers values(70, "Rhino");
INSERT into transformers values(71, "Yoketron");
INSERT into transformers values(72, "Quickmix");
INSERT into transformers values(73, "Ransack");
INSERT into transformers values(74, "Graphy");
INSERT into transformers values(75, "Checkpoint");
INSERT into transformers values(76, "Moon Jet");
INSERT into transformers values(77, "Shot Hole");
INSERT into transformers values(78, "Deep Dive");
INSERT into transformers values(79, "Grand Hog");
INSERT into transformers values(80, "Darkwing");
INSERT into transformers values(81, "Dodger");
INSERT into transformers values(82, "Needler");
INSERT into transformers values(83, "Catgut");
INSERT into transformers values(84, "Spittor");
INSERT into transformers values(85, "Magna Stampede");
INSERT into transformers values(86, "Tomaandi");
INSERT into transformers values(87, "Fireflight");
INSERT into transformers values(88, "Telus");
INSERT into transformers values(89, "PickUp");
INSERT into transformers values(90, "Filter");
INSERT into transformers values(91, "Magnificus");
INSERT into transformers values(92, "Downshift");
INSERT into transformers values(93, "Violator");
INSERT into transformers values(94, "Ikard");
INSERT into transformers values(95, "Escargon");
INSERT into transformers values(96, "Wars");
INSERT into transformers values(97, "Airachnid");
INSERT into transformers values(98, "Blowout");
INSERT into transformers values(99, "Quickslinger");
INSERT into transformers values(100, "Kakuryu");
INSERT into transformers values(101, "Aftershock");
INSERT into transformers values(102, "Megazarak");
INSERT into transformers values(103, "Groundbreaker");
INSERT into transformers values(104, "Suppressor");
INSERT into transformers values(105, "Glyph");
INSERT into transformers values(106, "Hubs");
INSERT into transformers values(107, "Under3");
INSERT into transformers values(108, "Ground Hog");
INSERT into transformers values(109, "Octopunch");
INSERT into transformers values(110, "Dropkick");
INSERT into transformers values(111, "Big Bang Prime");
INSERT into transformers values(112, "Blood");
INSERT into transformers values(113, "Rockblade");
INSERT into transformers values(114, "Shockblast");
INSERT into transformers values(115, "Wire Tap V20");
INSERT into transformers values(116, "Sandstorm");
INSERT into transformers values(117, "Sights");
INSERT into transformers values(118, "Throttle");
INSERT into transformers values(119, "Chrome");
INSERT into transformers values(120, "Skystalker");
INSERT into transformers values(121, "Flame");
INSERT into transformers values(122, "Motormouth");
INSERT into transformers values(123, "Sea Spray");
INSERT into transformers values(124, "Oceanglide");
INSERT into transformers values(125, "Override");
INSERT into transformers values(126, "DoomLock");
INSERT into transformers values(127, "Buzzbomb");
INSERT into transformers values(128, "King Atlas");
INSERT into transformers values(129, "Free Wheeler");
INSERT into transformers values(130, "Space Case");
INSERT into transformers values(131, "Overbite");
INSERT into transformers values(132, "Tonbot");
INSERT into transformers values(133, "Swerve");
INSERT into transformers values(134, "Drill Bit");
INSERT into transformers values(135, "Grindor");
INSERT into transformers values(136, "Waspinator");
INSERT into transformers values(137, "Gaihawk");
INSERT into transformers values(138, "Retrax");
INSERT into transformers values(139, "The Fallen");
INSERT into transformers values(140, "Cryotek");
INSERT into transformers values(141, "Daytonus");
INSERT into transformers values(142, "Boltax");
INSERT into transformers values(143, "Quench");
INSERT into transformers values(144, "Slide");
INSERT into transformers values(145, "Fortress Maximus");
INSERT into transformers values(146, "Mechatron");
INSERT into transformers values(147, "Flip Sides");
INSERT into transformers values(148, "Sizzle");
INSERT into transformers values(149, "Arcee");
INSERT into transformers values(150, "Swoop");
INSERT into transformers values(151, "Longtooth");
INSERT into transformers values(152, "Iota Supreme");
INSERT into transformers values(153, "Gilmer");
INSERT into transformers values(154, "Bazooka");
INSERT into transformers values(155, "Tread Bolt");
INSERT into transformers values(156, "Terradive");
INSERT into transformers values(157, "Omega Prime");
INSERT into transformers values(158, "Evac");
INSERT into transformers values(159, "Neutro");
INSERT into transformers values(160, "Basher");
INSERT into transformers values(161, "Gizmo");
INSERT into transformers values(162, "Prime Nova");
INSERT into transformers values(163, "Power Up VT6");
INSERT into transformers values(164, "Bodyblock");
INSERT into transformers values(165, "Buckshot");
INSERT into transformers values(166, "Slugfest");
INSERT into transformers values(167, "Horsepower");
INSERT into transformers values(168, "Autotrooper");
INSERT into transformers values(169, "Astrotrain");
INSERT into transformers values(170, "XGunner");
INSERT into transformers values(171, "Breacher");
INSERT into transformers values(172, "Clipper");
INSERT into transformers values(173, "Joe");
INSERT into transformers values(174, "Holepunch");
INSERT into transformers values(175, "Talon");
INSERT into transformers values(176, "Swindle");
INSERT into transformers values(177, "Hoist");
INSERT into transformers values(178, "WipeOut");
INSERT into transformers values(179, "Siren");
INSERT into transformers values(180, "Razor Claw");
INSERT into transformers values(181, "Gunlift");
INSERT into transformers values(182, "Zeta Supreme");
INSERT into transformers values(183, "Autolauncher");
INSERT into transformers values(184, "Carnivac");
INSERT into transformers values(185, "AntiBlaze");
INSERT into transformers values(186, "Angela");
INSERT into transformers values(187, "Roadburner");
INSERT into transformers values(188, "High Wire");
INSERT into transformers values(189, "Powerglide");
INSERT into transformers values(190, "Chameleon");
INSERT into transformers values(191, "Snare");
INSERT into transformers values(192, "Treadbolt");
INSERT into transformers values(193, "Movor");
INSERT into transformers values(194, "Finback");
INSERT into transformers values(195, "Skyblast");
INSERT into transformers values(196, "CopTur");
INSERT into transformers values(197, "Nemesis Strika");
INSERT into transformers values(198, "Quickswitch");
INSERT into transformers values(199, "Refuser");
INSERT into transformers values(200, "Kickback");
INSERT into transformers values(201, "Scrapheap ");
INSERT into transformers values(202, "Excavator");
INSERT into transformers values(203, "Shrapnel");
INSERT into transformers values(204, "Gredator");
INSERT into transformers values(205, "Bulkhead");
INSERT into transformers values(206, "Electro");
INSERT into transformers values(207, "Boltflash");
INSERT into transformers values(208, "Rippersnapper");
INSERT into transformers values(209, "Strika");
INSERT into transformers values(210, "Brushguard");
INSERT into transformers values(211, "CatSCAN");
INSERT into transformers values(212, "Flash");
INSERT into transformers values(213, "Slayride");
INSERT into transformers values(214, "Brimstone");
INSERT into transformers values(215, "Road Fire");
INSERT into transformers values(216, "Starcatcher");
INSERT into transformers values(217, "Broadside");
INSERT into transformers values(218, "Earthquake");
INSERT into transformers values(219, "Slap Dash");
INSERT into transformers values(220, "Dirge ");
INSERT into transformers values(221, "Rollout");
INSERT into transformers values(222, "Godbomber");
INSERT into transformers values(223, "Moonradar");
INSERT into transformers values(224, "Liege Maximo");
INSERT into transformers values(225, "Piranacon");
INSERT into transformers values(226, "Sixshot");
INSERT into transformers values(227, "Acid Storm");
INSERT into transformers values(228, "Wildrider");
INSERT into transformers values(229, "Drag Strip");
INSERT into transformers values(230, "Blight");
INSERT into transformers values(231, "Blastmaster");
INSERT into transformers values(232, "Jackhammer");
INSERT into transformers values(233, "Bluestreak ");
INSERT into transformers values(234, "Autojetter");
INSERT into transformers values(235, "Torque Gain");
INSERT into transformers values(236, "Jazz");
INSERT into transformers values(237, "Smokejumper");
INSERT into transformers values(238, "Snarler");
INSERT into transformers values(239, "Runway");
INSERT into transformers values(240, "Dualor");
INSERT into transformers values(241, "PsychoOrb");
INSERT into transformers values(242, "Sparkstalker");
INSERT into transformers values(243, "Mol");
INSERT into transformers values(244, "Jetfire ");
INSERT into transformers values(245, "Kraken");
INSERT into transformers values(246, "MicroConstructicon");
INSERT into transformers values(247, "Bonecrusher");
INSERT into transformers values(248, "Primus");
INSERT into transformers values(249, "Theta Supreme");
INSERT into transformers values(250, "Sunstorm");
INSERT into transformers values(251, "Great Cannon");
INSERT into transformers values(252, "Tripredacus");
INSERT into transformers values(253, "Oil Slick");
INSERT into transformers values(254, "Hover");
INSERT into transformers values(255, "Lockdown");
INSERT into transformers values(256, "Bullet");
INSERT into transformers values(257, "Reflector");
INSERT into transformers values(258, "Rage");
INSERT into transformers values(259, "Onslaught");
INSERT into transformers values(260, "Stopgap");
INSERT into transformers values(261, "Firebot");
INSERT into transformers values(262, "Flatfoot");
INSERT into transformers values(263, "Crosscut");
INSERT into transformers values(264, "Jack");
INSERT into transformers values(265, "Backstop");
INSERT into transformers values(266, "Path Finder");
INSERT into transformers values(267, "Treadshot");
INSERT into transformers values(268, "Axe");
INSERT into transformers values(269, "Dark Jet");
INSERT into transformers values(270, "Rumble");
INSERT into transformers values(271, "Drillbuster");
INSERT into transformers values(272, "Phoenix");
INSERT into transformers values(273, "Tote");
INSERT into transformers values(274, "Grand Slam");
INSERT into transformers values(275, "Wind Sheer");
INSERT into transformers values(276, "Hooligan");
INSERT into transformers values(277, "Tacker");
INSERT into transformers values(278, "Overbite ");
INSERT into transformers values(279, "Takedown");
INSERT into transformers values(280, "Circuit");
INSERT into transformers values(281, "Rad");
INSERT into transformers values(282, "Hyperdrive");
INSERT into transformers values(283, "Galaxy Shuttle");
INSERT into transformers values(284, "Man of Iron");
INSERT into transformers values(285, "Octane");
INSERT into transformers values(286, "Scamper");
INSERT into transformers values(287, "Night Viper");
INSERT into transformers values(288, "High Jump");
INSERT into transformers values(289, "Antagony");
INSERT into transformers values(290, "Supersonic");
INSERT into transformers values(291, "Bullhorn");
INSERT into transformers values(292, "Blades");
INSERT into transformers values(293, "SixGun");
INSERT into transformers values(294, "Brainstorm");
INSERT into transformers values(295, "Crumble");
INSERT into transformers values(296, "Camaro");
INSERT into transformers values(297, "The Keeper");
INSERT into transformers values(298, "Tidal Wave ");
INSERT into transformers values(299, "Liokaiser");
INSERT into transformers values(300, "Lightspeed");
INSERT into transformers values(301, "Joyride");
INSERT into transformers values(302, "Ravage");
INSERT into transformers values(303, "Sawtooth");
INSERT into transformers values(304, "Atlan");
INSERT into transformers values(305, "Ironworks");
INSERT into transformers values(306, "Cliffjumper");
INSERT into transformers values(307, "Flamewar");
INSERT into transformers values(308, "Soundwave");
INSERT into transformers values(309, "Beetle");
INSERT into transformers values(310, "Searchlight");
INSERT into transformers values(311, "Venom");
INSERT into transformers values(312, "Cyclis");
INSERT into transformers values(313, "Rapticon");
INSERT into transformers values(314, "Fire Chief");
INSERT into transformers values(315, "Highbrow");
INSERT into transformers values(316, "Ascentor");
INSERT into transformers values(317, "Demolishor");
INSERT into transformers values(318, "Damper");
INSERT into transformers values(319, "Pounce");
INSERT into transformers values(320, "Omega SPREEM");
INSERT into transformers values(321, "Roulette");
INSERT into transformers values(322, "Meantime");
INSERT into transformers values(323, "Fangry");
INSERT into transformers values(324, "Jetstream");
INSERT into transformers values(325, "Stormcloud");
INSERT into transformers values(326, "Savage Noble");
INSERT into transformers values(327, "Beta Supreme");
INSERT into transformers values(328, "Wingblazer");
INSERT into transformers values(329, "Orcanoch");
INSERT into transformers values(330, "Deadbolt");
INSERT into transformers values(331, "Dispensor");
INSERT into transformers values(332, "Sunburn");
INSERT into transformers values(333, "Drivetrain");
INSERT into transformers values(334, "Armada");
INSERT into transformers values(335, "Sixtrain");
INSERT into transformers values(336, "Adventas");
INSERT into transformers values(337, "Hardtop");
INSERT into transformers values(338, "Stonecrucher");
INSERT into transformers values(339, "ElitaOne");
INSERT into transformers values(340, "Quickstrike");
INSERT into transformers values(341, "Omega Supreme");
INSERT into transformers values(342, "Grapple");
INSERT into transformers values(343, "Crankcase");
INSERT into transformers values(344, "OverRun ");
INSERT into transformers values(345, "Snap Trap");
INSERT into transformers values(346, "Straxus");
INSERT into transformers values(347, "Laserbeak");
INSERT into transformers values(348, "Ichibi");
INSERT into transformers values(349, "Darkray");
INSERT into transformers values(350, "Magnum");
INSERT into transformers values(351, "Gnaw");
INSERT into transformers values(352, "Spiral");
INSERT into transformers values(353, "Excellion");
INSERT into transformers values(354, "Heave");
INSERT into transformers values(355, "Scattorbrain");
INSERT into transformers values(356, "Deathsaurus");
INSERT into transformers values(357, "Fire Road");
INSERT into transformers values(358, "Hell Buzzsaw");
INSERT into transformers values(359, "Turmoil");
INSERT into transformers values(360, "Moon");
INSERT into transformers values(361, "Gairyu");
INSERT into transformers values(362, "Breakaway");
INSERT into transformers values(363, "Gunrunner");
INSERT into transformers values(364, "Socket");
INSERT into transformers values(365, "SkidZ");
INSERT into transformers values(366, "Furao");
INSERT into transformers values(367, "Poison Bite");
INSERT into transformers values(368, "Barrel Roll");
INSERT into transformers values(369, "HeavyLiftor");
INSERT into transformers values(370, "Plug");
INSERT into transformers values(371, "Windcharger");
INSERT into transformers values(372, "Stiletto");
INSERT into transformers values(373, "Insecticon");
INSERT into transformers values(374, "Thrust");
INSERT into transformers values(375, "Razorbeast");
INSERT into transformers values(376, "RBlade");
INSERT into transformers values(377, "Ravenus");
INSERT into transformers values(378, "Refute");
INSERT into transformers values(379, "Fastlane");
INSERT into transformers values(380, "Diveplane");
INSERT into transformers values(381, "Bit");
INSERT into transformers values(382, "Depth Charge");
INSERT into transformers values(383, "Blast Master");
INSERT into transformers values(384, "Armorhide");
INSERT into transformers values(385, "Skywave");
INSERT into transformers values(386, "Undertow");
INSERT into transformers values(387, "Sixturbo");
INSERT into transformers values(388, "Longview");
INSERT into transformers values(389, "Shotbomber");
INSERT into transformers values(390, "Sonic Bomber");
INSERT into transformers values(391, "Darkstream");
INSERT into transformers values(392, "Deepdive");
INSERT into transformers values(393, "Line");
INSERT into transformers values(394, "RacknRuin");
INSERT into transformers values(395, "Iguanus");
INSERT into transformers values(396, "Megabolt");
INSERT into transformers values(397, "Glasspit");
INSERT into transformers values(398, "Quasar");
INSERT into transformers values(399, "Rapid Run");
INSERT into transformers values(400, "Air Raid");
INSERT into transformers values(401, "Grand");
INSERT into transformers values(402, "Road Ranger");
INSERT into transformers values(403, "Safety");
INSERT into transformers values(404, "Speeder");
INSERT into transformers values(405, "Devcon");
INSERT into transformers values(406, "Botanica");
INSERT into transformers values(407, "Wheelrun");
INSERT into transformers values(408, "Axor");
INSERT into transformers values(409, "Skyboom");
INSERT into transformers values(410, "Frostbite");
INSERT into transformers values(411, "Slag");
INSERT into transformers values(412, "Tyrannitron");
INSERT into transformers values(413, "Jaruga");
INSERT into transformers values(414, "Powerdashers");
INSERT into transformers values(415, "Rotorstorm");
INSERT into transformers values(416, "Starscream");
INSERT into transformers values(417, "Storm Surge");
INSERT into transformers values(418, "Deadlift");
INSERT into transformers values(419, "Rodney");
INSERT into transformers values(420, "Staxx");
INSERT into transformers values(421, "Shortround");
INSERT into transformers values(422, "Moonrock");
INSERT into transformers values(423, "Brunt");
INSERT into transformers values(424, "Aurik");
INSERT into transformers values(425, "Randy");
INSERT into transformers values(426, "Remedy");
INSERT into transformers values(427, "Caliburn");
INSERT into transformers values(428, "Decepticharge");
INSERT into transformers values(429, "Wedge Major");
INSERT into transformers values(430, "Chop Shop");
INSERT into transformers values(431, "Slapper");
INSERT into transformers values(432, "Rosanna");
INSERT into transformers values(433, "Backbeat");
INSERT into transformers values(434, "Outback");
INSERT into transformers values(435, "Rung");
INSERT into transformers values(436, "Break");
INSERT into transformers values(437, "Thunderclash");
INSERT into transformers values(438, "FullTilt");
INSERT into transformers values(439, "Dark Scream");
INSERT into transformers values(440, "Springer");
INSERT into transformers values(441, "Apexus");
INSERT into transformers values(442, "Rodimus Prime");
INSERT into transformers values(443, "Material");
INSERT into transformers values(444, "Deadhour");
INSERT into transformers values(445, "Railspike");
INSERT into transformers values(446, "Convertor");
INSERT into transformers values(447, "Chainclaw");
INSERT into transformers values(448, "Magnaboss");
INSERT into transformers values(449, "Shockwave");
INSERT into transformers values(450, "Lucas");
INSERT into transformers values(451, "Drago Yell");
INSERT into transformers values(452, "Doubledealer");
INSERT into transformers values(453, "Inferno");
INSERT into transformers values(454, "Abominus");
INSERT into transformers values(455, "ElitaOne ");
INSERT into transformers values(456, "Roughstuff");
INSERT into transformers values(457, "Warmonger");
INSERT into transformers values(458, "Duststorm");
INSERT into transformers values(459, "Skipjack");
INSERT into transformers values(460, "HunGrrr");
INSERT into transformers values(461, "Stardust");
INSERT into transformers values(462, "Slapdash");
INSERT into transformers values(463, "Powerpunch");
INSERT into transformers values(464, "Magmatron");
INSERT into transformers values(465, "Snapdragon");
INSERT into transformers values(466, "Bighorn");
INSERT into transformers values(467, "Rumbler");
INSERT into transformers values(468, "Triton");
INSERT into transformers values(469, "Reptilion");
INSERT into transformers values(470, "Star Upper");
INSERT into transformers values(471, "Speed Dial 800");
INSERT into transformers values(472, "Bug General");
INSERT into transformers values(473, "Volt");
INSERT into transformers values(474, "Powerdive");
INSERT into transformers values(475, "Schema");
INSERT into transformers values(476, "Hammerstrike");
INSERT into transformers values(477, "Cutthroat");
INSERT into transformers values(478, "Trizer");
INSERT into transformers values(479, "Longrack");
INSERT into transformers values(480, "Apelinq");
INSERT into transformers values(481, "Sprocket");
INSERT into transformers values(482, "Mirage GT");
INSERT into transformers values(483, "Blot");
INSERT into transformers values(484, "Jetstorm");
INSERT into transformers values(485, "Scoop");
INSERT into transformers values(486, "Smeltdown");
INSERT into transformers values(487, "Deftwing");
INSERT into transformers values(488, "HorriBull");
INSERT into transformers values(489, "Sparkplug");
INSERT into transformers values(490, "Pyro");
INSERT into transformers values(491, "Blockrock");
INSERT into transformers values(492, "Bilge");
INSERT into transformers values(493, "Flashpoint");
INSERT into transformers values(494, "Holi");
INSERT into transformers values(495, "Wingspan");
INSERT into transformers values(496, "Road Pig");
INSERT into transformers values(497, "Skyfall");
INSERT into transformers values(498, "Vortex");
INSERT into transformers values(499, "Flare Jet");
INSERT into transformers values(500, "Dirt Boss");
INSERT into transformers values(501, "Phaser");
INSERT into transformers values(502, "Preditron");
INSERT into transformers values(503, "Hosehead");
INSERT into transformers values(504, "Arachnid");
INSERT into transformers values(505, "Thundercracker");
INSERT into transformers values(506, "Strikedown");
INSERT into transformers values(507, "Silverbolt Major");
INSERT into transformers values(508, "High Beam");
INSERT into transformers values(509, "Road Hazard");
INSERT into transformers values(510, "Mainframe");
INSERT into transformers values(511, "Greatshot");
INSERT into transformers values(512, "Buster");
INSERT into transformers values(513, "Sunrunner");
INSERT into transformers values(514, "Hot Shot");
INSERT into transformers values(515, "Inferno ");
INSERT into transformers values(516, "Landshark");
INSERT into transformers values(517, "Road Hugger");
INSERT into transformers values(518, "Fusion");
INSERT into transformers values(519, "Clamp Down");
INSERT into transformers values(520, "Gran");
INSERT into transformers values(521, "OverRun");
INSERT into transformers values(522, "Plier");
INSERT into transformers values(523, "Beam Rider");
INSERT into transformers values(524, "Squawkbox");
INSERT into transformers values(525, "Archadis");
INSERT into transformers values(526, "Jetblade");
INSERT into transformers values(527, "Skyquake");
INSERT into transformers values(528, "Night Beat 7");
INSERT into transformers values(529, "Killbison");
INSERT into transformers values(530, "RoTor");
INSERT into transformers values(531, "Windy");
INSERT into transformers values(532, "Decibel");
INSERT into transformers values(533, "Padlock");
INSERT into transformers values(534, "Sixwing");
INSERT into transformers values(535, "Drill Nuts");
INSERT into transformers values(536, "Beachcomber");
INSERT into transformers values(537, "Mindse");
INSERT into transformers values(538, "Sinnertwin");
INSERT into transformers values(539, "TripUp");
INSERT into transformers values(540, "Obsidian");
INSERT into transformers values(541, "BombBurst");
INSERT into transformers values(542, "Scarem");
INSERT into transformers values(543, "Starscream ");
INSERT into transformers values(544, "Flint");
INSERT into transformers values(545, "Scrounges");
INSERT into transformers values(546, "Ranger");
INSERT into transformers values(547, "Grimstone");
INSERT into transformers values(548, "Skyhopper");
INSERT into transformers values(549, "Waver");
INSERT into transformers values(550, "Sky High");
INSERT into transformers values(551, "Top Gear");
INSERT into transformers values(552, "Turbofire");
INSERT into transformers values(553, "Tentakil");
INSERT into transformers values(554, "BB ");
INSERT into transformers values(555, "Doublecross");
INSERT into transformers values(556, "Beacon");
INSERT into transformers values(557, "Scrash");
INSERT into transformers values(558, "Eta Supreme");
INSERT into transformers values(559, "Tracks");
INSERT into transformers values(560, "Deadeye");
INSERT into transformers values(561, "Radrogue");
INSERT into transformers values(562, "Sharp Edge");
INSERT into transformers values(563, "Buzzsaw");
INSERT into transformers values(564, "Raiden");
INSERT into transformers values(565, "Smokesniper");
INSERT into transformers values(566, "Jhiaxus");
INSERT into transformers values(567, "Stampy");
INSERT into transformers values(568, "Snarl");
INSERT into transformers values(569, "TaleOff");
INSERT into transformers values(570, "Aquastar");
INSERT into transformers values(571, "Prima");
INSERT into transformers values(572, "Volks");
INSERT into transformers values(573, "Backstreet");
INSERT into transformers values(574, "Gears");
INSERT into transformers values(575, "Wildspark");
INSERT into transformers values(576, "Smolder");
INSERT into transformers values(577, "Wedge Shape");
INSERT into transformers values(578, "Frenzy ");
INSERT into transformers values(579, "Sinker");
INSERT into transformers values(580, "Ironside");
INSERT into transformers values(581, "Landfill");
INSERT into transformers values(582, "Road Rage");
INSERT into transformers values(583, "Perceptor");
INSERT into transformers values(584, "Hyperion");
INSERT into transformers values(585, "Steelgrave");
INSERT into transformers values(586, "Shuttle Gunner");
INSERT into transformers values(587, "Ratchet");
INSERT into transformers values(588, "Apeface");
INSERT into transformers values(589, "Sonar");
INSERT into transformers values(590, "Skyburst");
INSERT into transformers values(591, "Mauler");
INSERT into transformers values(592, "Eagle Eye");
INSERT into transformers values(593, "SkyByte");
INSERT into transformers values(594, "The Student");
INSERT into transformers values(595, "Navigator");
INSERT into transformers values(596, "Menasor");
INSERT into transformers values(597, "Hook");
INSERT into transformers values(598, "Optimus Prime");
INSERT into transformers values(599, "Alice");
INSERT into transformers values(600, "Clench");
INSERT into transformers values(601, "Wing Saber");
INSERT into transformers values(602, "Dirge");
INSERT into transformers values(603, "Birdbrain");
INSERT into transformers values(604, "Mindwipe");
INSERT into transformers values(605, "Crossblades");
INSERT into transformers values(606, "Big Daddy");
INSERT into transformers values(607, "NeoWheel");
INSERT into transformers values(608, "Strongarm");
INSERT into transformers values(609, "Seizer");
INSERT into transformers values(610, "Digger");
INSERT into transformers values(611, "Rotorbolt");
INSERT into transformers values(612, "SixSpeed");
INSERT into transformers values(613, "Falcia");
INSERT into transformers values(614, "LicketySplit");
INSERT into transformers values(615, "Terragator");
INSERT into transformers values(616, "Hacker X3");
INSERT into transformers values(617, "Shadow Striker");
INSERT into transformers values(618, "Backblast");
INSERT into transformers values(619, "Overkill");
INSERT into transformers values(620, "Tracer");
INSERT into transformers values(621, "Skyglide");
INSERT into transformers values(622, "Moscardo");
INSERT into transformers values(623, "Greaser");
INSERT into transformers values(624, "Crankstart");
INSERT into transformers values(625, "Road Rocket");
INSERT into transformers values(626, "BrakeNeck");
INSERT into transformers values(627, "Bruticus");
INSERT into transformers values(628, "Nutshell");
INSERT into transformers values(629, "Windrazor");
INSERT into transformers values(630, "Carrera");
INSERT into transformers values(631, "Dipstick");
INSERT into transformers values(632, "Stepper");
INSERT into transformers values(633, "Synapse");
INSERT into transformers values(634, "Iron Lift");
INSERT into transformers values(635, "Fixit");
INSERT into transformers values(636, "Vice Grip");
INSERT into transformers values(637, "Meanstreak");
INSERT into transformers values(638, "Skyhammer");
INSERT into transformers values(639, "Noise");
INSERT into transformers values(640, "Piston");
INSERT into transformers values(641, "Saber");
INSERT into transformers values(642, "Backslash");
INSERT into transformers values(643, "Deep Cover");
INSERT into transformers values(644, "Grease");
INSERT into transformers values(645, "Roller Force");
INSERT into transformers values(646, "Scuba");
INSERT into transformers values(647, "Unicron");
INSERT into transformers values(648, "Shouki");
INSERT into transformers values(649, "Weirdwolf");
INSERT into transformers values(650, "Brawl ");
INSERT into transformers values(651, "Spaceshot");
INSERT into transformers values(652, "Skalor");
INSERT into transformers values(653, "Overload");
INSERT into transformers values(654, "Long Haul");
INSERT into transformers values(655, "Missile Run");
INSERT into transformers values(656, "Midship");
INSERT into transformers values(657, "Motorhead");
INSERT into transformers values(658, "Knockdown");
INSERT into transformers values(659, "Sparkcrusher");
INSERT into transformers values(660, "Bantor");
INSERT into transformers values(661, "Chromebite");
INSERT into transformers values(662, "Traachon");
INSERT into transformers values(663, "KickOff");
INSERT into transformers values(664, "Glide");
INSERT into transformers values(665, "Charger");
INSERT into transformers values(666, "Mach Road");
INSERT into transformers values(667, "Repugnus");
INSERT into transformers values(668, "Dauros");
INSERT into transformers values(669, "Wideload");
INSERT into transformers values(670, "Wide Load");
INSERT into transformers values(671, "Thundercracler");
INSERT into transformers values(672, "Huffer");
INSERT into transformers values(673, "Chromedome");
INSERT into transformers values(674, "Scalpel");
INSERT into transformers values(675, "Tomahawk");
INSERT into transformers values(676, "FullBarrel");
INSERT into transformers values(677, "Mudslinger");
INSERT into transformers values(678, "Noise Effect");
INSERT into transformers values(679, "Sentinel Prime");
INSERT into transformers values(680, "Powerbomb");
INSERT into transformers values(681, "AstroSinker");
INSERT into transformers values(682, "Aquablast");
INSERT into transformers values(683, "Pointblank");
INSERT into transformers values(684, "Nitrostreak");
INSERT into transformers values(685, "Predaking");
INSERT into transformers values(686, "Bolar");
INSERT into transformers values(687, "Hardspark");
INSERT into transformers values(688, "Spin Road");
INSERT into transformers values(689, "Longhorn");
INSERT into transformers values(690, "Pinpoint");
INSERT into transformers values(691, "Windbreaker");
INSERT into transformers values(692, "Headstrong");
INSERT into transformers values(693, "Sweeps");
INSERT into transformers values(694, "Accel");
INSERT into transformers values(695, "Wheeljack");
INSERT into transformers values(696, "Discharge");
INSERT into transformers values(697, "Borehole");
INSERT into transformers values(698, "Safeguard");
INSERT into transformers values(699, "Roadbuster");
INSERT into transformers values(700, "Schyte");
INSERT into transformers values(701, "Thrasher");
INSERT into transformers values(702, "Incinerator");
INSERT into transformers values(703, "Slugslinger");
INSERT into transformers values(704, "Slicer");
INSERT into transformers values(705, "Cicadacon");
INSERT into transformers values(706, "Powerhug");
INSERT into transformers values(707, "Tantrum");
INSERT into transformers values(708, "Tigerhawk");
INSERT into transformers values(709, "Nemesis Prime");
INSERT into transformers values(710, "Oiler");
INSERT into transformers values(711, "Gatoraider");
INSERT into transformers values(712, "Groundshaker");
INSERT into transformers values(713, "Big Shot");
INSERT into transformers values(714, "Gigatron");
INSERT into transformers values(715, "Hardhead");
INSERT into transformers values(716, "Alpha Supreme");
INSERT into transformers values(717, "Ramjet");
INSERT into transformers values(718, "Triceradon");
INSERT into transformers values(719, "Jipe");
INSERT into transformers values(720, "Flywheels");
INSERT into transformers values(721, "Fracture");
INSERT into transformers values(722, "Gripper");
INSERT into transformers values(723, "Tyrest");
INSERT into transformers values(724, "Crest");
INSERT into transformers values(725, "Surge");
INSERT into transformers values(726, "Zaur");
INSERT into transformers values(727, "Chopsaw");
INSERT into transformers values(728, "Wingthing");
INSERT into transformers values(729, "Detour");
INSERT into transformers values(730, "Sparkride");
INSERT into transformers values(731, "Gigant Bomb");
INSERT into transformers values(732, "Lyzack");
INSERT into transformers values(733, "Screw");
INSERT into transformers values(734, "Emirate Xenon");
INSERT into transformers values(735, "Last Autobot");
INSERT into transformers values(736, "Sentinel Maximus");
INSERT into transformers values(737, "Zetca");
INSERT into transformers values(738, "Big Convoy");
INSERT into transformers values(739, "Ferak");
INSERT into transformers values(740, "Nautilator");
INSERT into transformers values(741, "Bruticus Maximus");
INSERT into transformers values(742, "Trenchmouth");
INSERT into transformers values(743, "Drillhorn");
INSERT into transformers values(744, "Turbo");
INSERT into transformers values(745, "Hubcap");
INSERT into transformers values(746, "Landslide");
INSERT into transformers values(747, "Alpha Prime");
INSERT into transformers values(748, "Minerva");
INSERT into transformers values(749, "Knockout");
INSERT into transformers values(750, "Tailgate");
INSERT into transformers values(751, "Treads");
INSERT into transformers values(752, "Injector");
INSERT into transformers values(753, "Spy Streak");
INSERT into transformers values(754, "Scattor");
INSERT into transformers values(755, "Slog");
INSERT into transformers values(756, "Air Hunter");
INSERT into transformers values(757, "Tackle");
INSERT into transformers values(758, "Megastorm ");
INSERT into transformers values(759, "Sureshock");
INSERT into transformers values(760, "Vanquish");
INSERT into transformers values(761, "Goshooter");
INSERT into transformers values(762, "Landcross");
INSERT into transformers values(763, "Saberback");
INSERT into transformers values(764, "Overair");
INSERT into transformers values(765, "Overdrive");
INSERT into transformers values(766, "Aquafend");
INSERT into transformers values(767, "Longarm");
INSERT into transformers values(768, "Stalker");
INSERT into transformers values(769, "Nexus Maximus ");
INSERT into transformers values(770, "Pipes");
INSERT into transformers values(771, "First Aid");
INSERT into transformers values(772, "Big Bang");
INSERT into transformers values(773, "Trannis");
INSERT into transformers values(774, "Archforce");
INSERT into transformers values(775, "Backwind");
INSERT into transformers values(776, "Crystal Widow");
INSERT into transformers values(777, "Landquake");
INSERT into transformers values(778, "Punch ");
INSERT into transformers values(779, "Runamuck");
INSERT into transformers values(780, "Wheel Blaze");
INSERT into transformers values(781, "Legout");
INSERT into transformers values(782, "Roadjet");
INSERT into transformers values(783, "Constructicon Maximus");
INSERT into transformers values(784, "Battle Unicorn");
INSERT into transformers values(785, "Footdemo");
INSERT into transformers values(786, "Atlas");
INSERT into transformers values(787, "PushButton");
INSERT into transformers values(788, "Paddles");
INSERT into transformers values(789, "Zapmaster");
INSERT into transformers values(790, "Reverse Convoy");
INSERT into transformers values(791, "Waspinator ");
INSERT into transformers values(792, "Backfire");
INSERT into transformers values(793, "Dial");
INSERT into transformers values(794, "Dirtbag");
INSERT into transformers values(795, "Detritus");
INSERT into transformers values(796, "Powerpinch");
INSERT into transformers values(797, "Braver");
INSERT into transformers values(798, "Caliburst");
INSERT into transformers values(799, "Iceberg");
INSERT into transformers values(800, "Icebird");
INSERT into transformers values(801, "Armordillo");
INSERT into transformers values(802, "Rabbicrater");
INSERT into transformers values(803, "Sunder");
INSERT into transformers values(804, "Fractyl");
INSERT into transformers values(805, "Drench");
INSERT into transformers values(806, "Gritbit");
INSERT into transformers values(807, "Streetstar");
INSERT into transformers values(808, "Hot Spot");
INSERT into transformers values(809, "Wildfly");
INSERT into transformers values(810, "Raise");
INSERT into transformers values(811, "Side Burn");
INSERT into transformers values(812, "Leeland");
INSERT into transformers values(813, "Bayonet");
INSERT into transformers values(814, "Buzz Saw");
INSERT into transformers values(815, "Lugnutz");
INSERT into transformers values(816, "Lugnut");
INSERT into transformers values(817, "Ricochet");
INSERT into transformers values(818, "Prowl 2");
INSERT into transformers values(819, "Squawktalk");
INSERT into transformers values(820, "Sentinel Major");
INSERT into transformers values(821, "Sari Sumdac");
INSERT into transformers values(822, "Thunder Arrow");
INSERT into transformers values(823, "Firestar");
INSERT into transformers values(824, "Mach Kick");
INSERT into transformers values(825, "Mugen");
INSERT into transformers values(826, "Speedstream");
INSERT into transformers values(827, "Trailbreaker");
INSERT into transformers values(828, "Seawatch");
INSERT into transformers values(829, "Buzzclaw");
INSERT into transformers values(830, "Manterror");
INSERT into transformers values(831, "Backbite");
INSERT into transformers values(832, "Stretch");
INSERT into transformers values(833, "King Poseidon");
INSERT into transformers values(834, "Santon");
INSERT into transformers values(835, "Rapido");
INSERT into transformers values(836, "Chro");
INSERT into transformers values(837, "Windmill");
INSERT into transformers values(838, "TowLine");
INSERT into transformers values(839, "Brake");
INSERT into transformers values(840, "Black Rorichi");
INSERT into transformers values(841, "Doryu");
INSERT into transformers values(842, "Cataclysm");
INSERT into transformers values(843, "Redline");
INSERT into transformers values(844, "Delta Supreme");
INSERT into transformers values(845, "Primal Major");
INSERT into transformers values(846, "Lancer");
INSERT into transformers values(847, "Blackarachnia ");
INSERT into transformers values(848, "Goryu");
INSERT into transformers values(849, "Photon T34");
INSERT into transformers values(850, "Pipo");
INSERT into transformers values(851, "Transmutate");
INSERT into transformers values(852, "Rollbar");
INSERT into transformers values(853, "Defensor");
INSERT into transformers values(854, "Nightcruz");
INSERT into transformers values(855, "BBoom");
INSERT into transformers values(856, "Graviton");
INSERT into transformers values(857, "Razorclaw");
INSERT into transformers values(858, "Triggerhappy");
INSERT into transformers values(859, "Razorbeam");
INSERT into transformers values(860, "Mixing");
INSERT into transformers values(861, "Sideways");
INSERT into transformers values(862, "Night Glider");
INSERT into transformers values(863, "Waverider");
INSERT into transformers values(864, "Silverbolt");
INSERT into transformers values(865, "Steelshot");
INSERT into transformers values(866, "Guzzle");
INSERT into transformers values(867, "Swashplate");
INSERT into transformers values(868, "Signal Flare");
INSERT into transformers values(869, "Bombshock");
INSERT into transformers values(870, "Roadhandler");
INSERT into transformers values(871, "Gnashteeh");
INSERT into transformers values(872, "Manta Ray");
INSERT into transformers values(873, "XBrawn");
INSERT into transformers values(874, "Shockwave ");
INSERT into transformers values(875, "Dreadwind");
INSERT into transformers values(876, "Blaze");
INSERT into transformers values(877, "Rhinox");
INSERT into transformers values(878, "Scalpel ");
INSERT into transformers values(879, "Dillo");
INSERT into transformers values(880, "Windsweeper");
INSERT into transformers values(881, "Lio Convoy");
INSERT into transformers values(882, "Calculus");
INSERT into transformers values(883, "Kappa Supreme");
INSERT into transformers values(884, "Double Punch");
INSERT into transformers values(885, "Doubleheader");
INSERT into transformers values(886, "Barricade");
INSERT into transformers values(887, "Heatwave");
INSERT into transformers values(888, "Wilder");
INSERT into transformers values(889, "Megaplex");
INSERT into transformers values(890, "Gran Arm");
INSERT into transformers values(891, "Dead End");
INSERT into transformers values(892, "Iron Claw");
INSERT into transformers values(893, "Cancer");
INSERT into transformers values(894, "Doubleclouder");
INSERT into transformers values(895, "Sunstreaker");
INSERT into transformers values(896, "Devastator");
INSERT into transformers values(897, "Terranotron");
INSERT into transformers values(898, "Motorstar");
INSERT into transformers values(899, "Gusher");
INSERT into transformers values(900, "Darklight");
INSERT into transformers values(901, "Dreadwing");
INSERT into transformers values(902, "Steamhammer");
INSERT into transformers values(903, "Cannonball");
INSERT into transformers values(904, "Booster X10");
INSERT into transformers values(905, "Bombshell");
INSERT into transformers values(906, "Scattershot");
INSERT into transformers values(907, "Breeze Master");
INSERT into transformers values(908, "Firetrap");
INSERT into transformers values(909, "Override Prime");
INSERT into transformers values(910, "Atomizer");
INSERT into transformers values(911, "Stripmine");
INSERT into transformers values(912, "Thunderblast");
INSERT into transformers values(913, "Hydradread");
INSERT into transformers values(914, "Reedman");
INSERT into transformers values(915, "Hopper");
INSERT into transformers values(916, "Diver");
INSERT into transformers values(917, "Groundpounder");
INSERT into transformers values(918, "Nightbeat");
INSERT into transformers values(919, "Ironlunge");
INSERT into transformers values(920, "Farsight T20");
INSERT into transformers values(921, "Hailstorm");
INSERT into transformers values(922, "Scattershot Major");
INSERT into transformers values(923, "Cloudburst");
INSERT into transformers values(924, "Thyristor");
INSERT into transformers values(925, "Moonracer");
INSERT into transformers values(926, "Howlback");
INSERT into transformers values(927, "Zardak");
INSERT into transformers values(928, "Carzap");
INSERT into transformers values(929, "Groove");
INSERT into transformers values(930, "HalfTrack");
INSERT into transformers values(931, "Liftor");
INSERT into transformers values(932, "Jawbreaker");
INSERT into transformers values(933, "Predacon");
INSERT into transformers values(934, "Vroom");
INSERT into transformers values(935, "Wingstun");
INSERT into transformers values(936, "Bludgeon");
INSERT into transformers values(937, "Sureshot");
INSERT into transformers values(938, "Frenzy");
INSERT into transformers values(939, "Trigger");
INSERT into transformers values(940, "Chromia");
INSERT into transformers values(941, "Command Ravage");
INSERT into transformers values(942, "Thunderwing");
INSERT into transformers values(943, "Bug Drone");
INSERT into transformers values(944, "Striker");
INSERT into transformers values(945, "San Diego");
INSERT into transformers values(946, "WreckGar");
INSERT into transformers values(947, "Nemesis Breaker");
INSERT into transformers values(948, "Spark");
INSERT into transformers values(949, "Rev");
INSERT into transformers values(950, "Megatron");
INSERT into transformers values(951, "Rattrap");
INSERT into transformers values(952, "Countdown");
INSERT into transformers values(953, "Treader");
INSERT into transformers values(954, "FlyUp");
INSERT into transformers values(955, "Undermine");
INSERT into transformers values(956, "Hellbat");
INSERT into transformers values(957, "Lens");
INSERT into transformers values(958, "Legs");
INSERT into transformers values(959, "Greasepit");
INSERT into transformers values(960, "Hotspark");
INSERT into transformers values(961, "Blue Bacchus");
INSERT into transformers values(962, "Sky Lynx");
INSERT into transformers values(963, "Bristleback");
INSERT into transformers values(964, "Metrodash");
INSERT into transformers values(965, "Sledge");
INSERT into transformers values(966, "Twin Twist");
INSERT into transformers values(967, "Leozak");
INSERT into transformers values(968, "Bumblebee ");
INSERT into transformers values(969, "Icepick");
INSERT into transformers values(970, "Tectonix");
INSERT into transformers values(971, "Ironfist");
INSERT into transformers values(972, "Highline 1070");
INSERT into transformers values(973, "Bugly");
INSERT into transformers values(974, "Payload");
INSERT into transformers values(975, "Dai Atlas");
INSERT into transformers values(976, "Runabout");
INSERT into transformers values(977, "Skyjack");
INSERT into transformers values(978, "Alpha Trion");
INSERT into transformers values(979, "PanHandler");
INSERT into transformers values(980, "Cruellock");
INSERT into transformers values(981, "Stonecruncher");
INSERT into transformers values(982, "MegaOctane");
INSERT into transformers values(983, "Monstructor");
INSERT into transformers values(984, "Leaf");
INSERT into transformers values(985, "Skullgrin");
INSERT into transformers values(986, "Spinister");
INSERT into transformers values(987, "Mixmaster");
INSERT into transformers values(988, "Wheelie");
INSERT into transformers values(989, "Sireen");
INSERT into transformers values(990, "Fireshot");
INSERT into transformers values(991, "Clocker");
INSERT into transformers values(992, "Hot Rod ");
INSERT into transformers values(993, "Midnight Express");
INSERT into transformers values(994, "Heavytread");
INSERT into transformers values(995, "Seawing");
INSERT into transformers values(996, "Glit");
INSERT into transformers values(997, "Axer");
INSERT into transformers values(998, "Wrecker Hook");
INSERT into transformers values(999, "Modus Prime");
INSERT into transformers values(1000, "Javil");
INSERT into transformers values(1001, "Glorean");
INSERT into transformers values(1002, "RunOver");
INSERT into transformers values(1003, "Tranquito");
INSERT into transformers values(1004, "Yardarm");
INSERT into transformers values(1005, "DJ");
INSERT into transformers values(1006, "Download");
INSERT into transformers values(1007, "Omega Sentinel");
INSERT into transformers values(1008, "Wreckloose");
INSERT into transformers values(1009, "Hurricane");
INSERT into transformers values(1010, "Gunbarrel");
INSERT into transformers values(1011, "Wrench");
INSERT into transformers values(1012, "Tarantulas");
INSERT into transformers values(1013, "Switch");
INSERT into transformers values(1014, "Tankor");
INSERT into transformers values(1015, "Scrapper");
INSERT into transformers values(1016, "Che");
INSERT into transformers values(1017, "Road Caesar");
INSERT into transformers values(1018, "Twirl");
INSERT into transformers values(1019, "Fearswoop");
INSERT into transformers values(1020, "Lugnut Supreme");
INSERT into transformers values(1021, "Sea Clamp");
INSERT into transformers values(1022, "Cheetor");
INSERT into transformers values(1023, "TerrorTread");
INSERT into transformers values(1024, "Cindersaur");
INSERT into transformers values(1025, "Chase");
INSERT into transformers values(1026, "Firebeast");
INSERT into transformers values(1027, "Rail Racer");
INSERT into transformers values(1028, "Mach");
INSERT into transformers values(1029, "Pincher");
INSERT into transformers values(1030, "Cloudraker");
INSERT into transformers values(1031, "Offshoot");
INSERT into transformers values(1032, "Mile");
INSERT into transformers values(1033, "Roadblock");
INSERT into transformers values(1034, "Catilla");
INSERT into transformers values(1035, "Metrotank");
INSERT into transformers values(1036, "Getaway");
INSERT into transformers values(1037, "Oval");
INSERT into transformers values(1038, "Flareup");
INSERT into transformers values(1039, "Datamine");
INSERT into transformers values(1040, "Kaput");
INSERT into transformers values(1041, "Grandus");
INSERT into transformers values(1042, "Thrust ");
INSERT into transformers values(1043, "Quantum");
INSERT into transformers values(1044, "Swindler");
INSERT into transformers values(1045, "Wingblade");
INSERT into transformers values(1046, "Checker Road");
INSERT into transformers values(1047, "Ejector");
INSERT into transformers values(1048, "AstroLine");
INSERT into transformers values(1049, "Brawn");
INSERT into transformers values(1050, "Vanguard");
INSERT into transformers values(1051, "Jolt ");
INSERT into transformers values(1052, "TapOut");
INSERT into transformers values(1053, "Ram Horn");
INSERT into transformers values(1054, "Cog ");
INSERT into transformers values(1055, "Tailwind");
INSERT into transformers values(1056, "Skater");
INSERT into transformers values(1057, "Clamp");
INSERT into transformers values(1058, "Tripwire");
INSERT into transformers values(1059, "Snapper");
INSERT into transformers values(1060, "Nightflight");
INSERT into transformers values(1061, "GADEP");
INSERT into transformers values(1062, "Cerebros");
INSERT into transformers values(1063, "Windrim");
INSERT into transformers values(1064, "Sideswipe");
INSERT into transformers values(1065, "Abacus");
INSERT into transformers values(1066, "Andromeda");
INSERT into transformers values(1067, "Calcar");
INSERT into transformers values(1068, "Zoom Out 25x");
INSERT into transformers values(1069, "Crosswise");
INSERT into transformers values(1070, "Salvage");
INSERT into transformers values(1071, "CrushBull");
INSERT into transformers values(1072, "Blitz");
INSERT into transformers values(1073, "Impactor Major");
INSERT into transformers values(1074, "Scorch");
INSERT into transformers values(1075, "Ginrai ");
INSERT into transformers values(1076, "Streetwise");
INSERT into transformers values(1077, "Buffalo Dump");
INSERT into transformers values(1078, "Kobushi");
INSERT into transformers values(1079, "Lione");
INSERT into transformers values(1080, "Stratosphere");
INSERT into transformers values(1081, "Hammer");
INSERT into transformers values(1082, "Dice");
INSERT into transformers values(1083, "Shokaract");
INSERT into transformers values(1084, "Reverb");
INSERT into transformers values(1085, "Sling");
INSERT into transformers values(1086, "Slamdance");
INSERT into transformers values(1087, "Dirt Rocket");
INSERT into transformers values(1088, "Slammer");
INSERT into transformers values(1089, "Computron");
INSERT into transformers values(1090, "Whirl");
INSERT into transformers values(1091, "Gingham");
INSERT into transformers values(1092, "Salvo");
INSERT into transformers values(1093, "Gauge");
INSERT into transformers values(1094, "Motorarm");
INSERT into transformers values(1095, "Metrobomb");
INSERT into transformers values(1096, "Elephorca");
INSERT into transformers values(1097, "TWrecks");
INSERT into transformers values(1098, "Dinotron");
INSERT into transformers values(1099, "Storm Cloud");
INSERT into transformers values(1100, "Snow Cat");
INSERT into transformers values(1101, "Spanner");
INSERT into transformers values(1102, "Bumblebee");
INSERT into transformers values(1103, "Gutcruncher");
INSERT into transformers values(1104, "Drancon");
INSERT into transformers values(1105, "Repticus");
INSERT into transformers values(1106, "Grimlock");
INSERT into transformers values(1107, "Bound Rogue");
INSERT into transformers values(1108, "Lightfoot");
INSERT into transformers values(1109, "Steeljaw");
INSERT into transformers values(1110, "Hacksaw");
INSERT into transformers values(1111, "Airazor");
INSERT into transformers values(1112, "Soundblaster");
INSERT into transformers values(1113, "Epsilon Supreme");
INSERT into transformers values(1114, "Monocle");
INSERT into transformers values(1115, "Thunderstick ");
INSERT into transformers values(1116, "Kup");
INSERT into transformers values(1117, "Cyclonus ");
INSERT into transformers values(1118, "Scorpulator");
INSERT into transformers values(1119, "Blast Off");
INSERT into transformers values(1120, "Quake");
INSERT into transformers values(1121, "Crunch");
INSERT into transformers values(1122, "Grindcore");
INSERT into transformers values(1123, "Laster");
INSERT into transformers values(1124, "Shatterpoint");
INSERT into transformers values(1125, "Betabear");
INSERT into transformers values(1126, "Grand Maximus");
INSERT into transformers values(1127, "Autocrusher");
INSERT into transformers values(1128, "Spinner");
INSERT into transformers values(1129, "Subsea");
INSERT into transformers values(1130, "DGo");
INSERT into transformers values(1131, "Kaen");
INSERT into transformers values(1132, "Meltdown");
INSERT into transformers values(1133, "Overcharge");
INSERT into transformers values(1134, "Desire");
INSERT into transformers values(1135, "Reachout");
INSERT into transformers values(1136, "Bump");
INSERT into transformers values(1137, "Landmine");
INSERT into transformers values(1138, "Nightstick");
INSERT into transformers values(1139, "Blastcharge");
INSERT into transformers values(1140, "Zaptrap");
INSERT into transformers values(1141, "Smokescreen");
INSERT into transformers values(1142, "Splashdown");
INSERT into transformers values(1143, "Erector");
INSERT into transformers values(1144, "Dug Base");
INSERT into transformers values(1145, "Bumper");
INSERT into transformers values(1146, "RestQ");
INSERT into transformers values(1147, "Waterlog");
INSERT into transformers values(1148, "Blitzwing");
INSERT into transformers values(1149, "Skids");
INSERT into transformers values(1150, "Squeezeplay");
INSERT into transformers values(1151, "Topspin");
INSERT into transformers values(1152, "Tailslide");
INSERT into transformers values(1153, "MegatronGalvatron");
INSERT into transformers values(1154, "FlatOut");
INSERT into transformers values(1155, "Sonic");
INSERT into transformers values(1156, "Dune Runner");
INSERT into transformers values(1157, "Falcon");
INSERT into transformers values(1158, "Yakuryu");
INSERT into transformers values(1159, "Windburn");
INSERT into transformers values(1160, "Blowpipe");
INSERT into transformers values(1161, "Seeker");
INSERT into transformers values(1162, "Battle Gaea");
INSERT into transformers values(1163, "Stinkbomb");
INSERT into transformers values(1164, "Slingshot");
INSERT into transformers values(1165, "Beastbox");
INSERT into transformers values(1166, "Skyfire");
INSERT into transformers values(1167, "Slipstream");
INSERT into transformers values(1168, "Metrotitan");
INSERT into transformers values(1169, "Freeboot");
INSERT into transformers values(1170, "Smokescreen ");
INSERT into transformers values(1171, "Goldbug");
INSERT into transformers values(1172, "Legion");
INSERT into transformers values(1173, "Fistfight");
INSERT into transformers values(1174, "Road Hauler ");
INSERT into transformers values(1175, "Dash");
INSERT into transformers values(1176, "Bad Boy");
INSERT into transformers values(1177, "Nautilus");
INSERT into transformers values(1178, "Getsuei");
INSERT into transformers values(1179, "Krok");
INSERT into transformers values(1180, "Pharma");
INSERT into transformers values(1181, "Dinobot");
INSERT into transformers values(1182, "Mantis");
INSERT into transformers values(1183, "Overflow");
INSERT into transformers values(1184, "Trypticon");
INSERT into transformers values(1185, "Battle Ravage");
INSERT into transformers values(1186, "Hot Spot Major");
INSERT into transformers values(1187, "Scrapmetal");
INSERT into transformers values(1188, "Emirate Xaaron");
INSERT into transformers values(1189, "Lobclaw");
INSERT into transformers values(1190, "Hydraulic");
INSERT into transformers values(1191, "Flamefeather");
INSERT into transformers values(1192, "Skywarp");
INSERT into transformers values(1193, "Megatron ");
INSERT into transformers values(1194, "Greenlight");
INSERT into transformers values(1195, "CyKill");
INSERT into transformers values(1196, "Swoop ");
INSERT into transformers values(1197, "Panther");
INSERT into transformers values(1198, "Combusta");
INSERT into transformers values(1199, "Double Clutch");
INSERT into transformers values(1200, "Starcloud");
INSERT into transformers values(1201, "Roadgrabber");
INSERT into transformers values(1202, "Target Hawk");
INSERT into transformers values(1203, "Rip Tide");
INSERT into transformers values(1204, "Scorponok");
INSERT into transformers values(1205, "Scavenger");
INSERT into transformers values(1206, "DirectHit");
INSERT into transformers values(1207, "Kirk");
INSERT into transformers values(1208, "Dropshot");
INSERT into transformers values(1209, "Makeshift");
INSERT into transformers values(1210, "RazorSharp");
INSERT into transformers values(1211, "Sixbuilder");
INSERT into transformers values(1212, "Oil Pan");
INSERT into transformers values(1213, "Effect");
INSERT into transformers values(1214, "Blackjack");
INSERT into transformers values(1215, "Grotusque");
INSERT into transformers values(1216, "Cohrada");
INSERT into transformers values(1217, "Jackpot");
INSERT into transformers values(1218, "Rampage");
INSERT into transformers values(1219, "Polar Claw");
INSERT into transformers values(1220, "Deluge");
INSERT into transformers values(1221, "Jetfire");
INSERT into transformers values(1222, "Abel");
INSERT into transformers values(1223, "Fallback");
INSERT into transformers values(1224, "Cyclonus");
INSERT into transformers values(1225, "Dion");
INSERT into transformers values(1226, "Powertrain");
INSERT into transformers values(1227, "Mirror");
INSERT into transformers values(1228, "Knock Out");
INSERT into transformers values(1229, "Bulletbike");
INSERT into transformers values(1230, "Cybershark");
INSERT into transformers values(1231, "Lazorbeak");
INSERT into transformers values(1232, "Fetch");
INSERT into transformers values(1233, "Rod");
INSERT into transformers values(1234, "9K");
INSERT into transformers values(1235, "Seaspray");
INSERT into transformers values(1236, "Retro");
INSERT into transformers values(1237, "Cluster");
INSERT into transformers values(1238, "Superion Maximus");
INSERT into transformers values(1239, "Superion");
INSERT into transformers values(1240, "Boss");
INSERT into transformers values(1241, "Throttler");
INSERT into transformers values(1242, "Chaingun");
INSERT into transformers values(1243, "Browning");
INSERT into transformers values(1244, "Raker");
INSERT into transformers values(1245, "Ramhorn");
INSERT into transformers values(1246, "Sixliner");
INSERT into transformers values(1247, "Factor");
INSERT into transformers values(1248, "Rav");
INSERT into transformers values(1249, "Metalhawk");
INSERT into transformers values(1250, "Sky Shadow");
INSERT into transformers values(1251, "Zapmap");
INSERT into transformers values(1252, "Drift ");
INSERT into transformers values(1253, "Star Saber");
INSERT into transformers values(1254, "Hot House");
INSERT into transformers values(1255, "K9");
INSERT into transformers values(1256, "Misfire");
INSERT into transformers values(1257, "Boater");
INSERT into transformers values(1258, "Heavy Tread");
INSERT into transformers values(1259, "Zoom Zoom");
INSERT into transformers values(1260, "Wheezel");
INSERT into transformers values(1261, "Brakedown");
INSERT into transformers values(1262, "Missile Master");
INSERT into transformers values(1263, "Barrage");
INSERT into transformers values(1264, "Missile Bull");
INSERT into transformers values(1265, "Leadfoot");
INSERT into transformers values(1266, "Shadow Jet");
INSERT into transformers values(1267, "Flattop");
INSERT into transformers values(1268, "Fizzle");
INSERT into transformers values(1269, "Legonis");
INSERT into transformers values(1270, "Seizan");
INSERT into transformers values(1271, "Flak");
INSERT into transformers values(1272, "Metroplex");
INSERT into transformers values(1273, "Sunspot");
INSERT into transformers values(1274, "Sharkticon");
INSERT into transformers values(1275, "Powerflash");
INSERT into transformers values(1276, "Divebomb");
INSERT into transformers values(1277, "Power Run");
INSERT into transformers values(1278, "Hyakurai");
INSERT into transformers values(1279, "Sidetrack");
INSERT into transformers values(1280, "Mirage");
INSERT into transformers values(1281, "Small Foot");
INSERT into transformers values(1282, "Geckobot");
INSERT into transformers values(1283, "Garboil");
INSERT into transformers values(1284, "Red Alert");
INSERT into transformers values(1285, "Blurr ");
INSERT into transformers values(1286, "Zangetsu");
INSERT into transformers values(1287, "Rotor");
INSERT into transformers values(1288, "Stockade");
INSERT into transformers values(1289, "Firecracker");
INSERT into transformers values(1290, "Bug Bite");
INSERT into transformers values(1291, "Fallen");
INSERT into transformers values(1292, "Survive");
INSERT into transformers values(1293, "Wolfang");
INSERT into transformers values(1294, "Stranglehold");
INSERT into transformers values(1295, "Stakeout");
INSERT into transformers values(1296, "Guiledart");
INSERT into transformers values(1297, "Solar");
INSERT into transformers values(1298, "Backtrack");
INSERT into transformers values(1299, "Fasttrack");
INSERT into transformers values(1300, "Element");
INSERT into transformers values(1301, "Spoil");
INSERT into transformers values(1302, "Terrorsaur");
INSERT into transformers values(1303, "Rodimus");
INSERT into transformers values(1304, "Rook");
INSERT into transformers values(1305, "Detectus");
INSERT into transformers values(1306, "Suiken");
INSERT into transformers values(1307, "Airwave");
INSERT into transformers values(1308, "Longrack Major");
INSERT into transformers values(1309, "Warhead");
INSERT into transformers values(1310, "Air Hammer");
INSERT into transformers values(1311, "Cosmos");
INSERT into transformers values(1312, "Lio Junior");
INSERT into transformers values(1313, "Fang");
INSERT into transformers values(1314, "Chopster");
INSERT into transformers values(1315, "Animus");
INSERT into transformers values(1316, "Black Shadow");
INSERT into transformers values(1317, "Submarauder");
INSERT into transformers values(1318, "Overlord");
INSERT into transformers values(1319, "Pinpointer");
INSERT into transformers values(1320, "Ruination");
INSERT into transformers values(1321, "Blazemaster");
INSERT into transformers values(1322, "Skydive");
INSERT into transformers values(1323, "Rocketbot");
INSERT into transformers values(1324, "Needlenose");
INSERT into transformers values(1325, "Optimus Primal");
INSERT into transformers values(1326, "Torque");
INSERT into transformers values(1327, "Ambulon");
INSERT into transformers values(1328, "Blaze Master");
INSERT into transformers values(1329, "Emissary");
INSERT into transformers values(1330, "Sedan");
INSERT into transformers values(1331, "Ironhide");
INSERT into transformers values(1332, "Doppler");
INSERT into transformers values(1333, "Stungun");
INSERT into transformers values(1334, "Tigatron");
INSERT into transformers values(1335, "Tripledacus");
INSERT into transformers values(1336, "Spy Shot 6");
INSERT into transformers values(1337, "Tornado");
INSERT into transformers values(1338, "Ego");
INSERT into transformers values(1339, "Tailwhip");
INSERT into transformers values(1340, "Impulsor");
INSERT into transformers values(1341, "Ratbat");
INSERT into transformers values(1342, "Steel Wind");
INSERT into transformers values(1343, "Guard City");
INSERT into transformers values(1344, "Hightower");
INSERT into transformers values(1345, "Blackout");
INSERT into transformers values(1346, "Krunix");
INSERT into transformers values(1347, "Bulge");
INSERT into transformers values(1348, "Overcast");
INSERT into transformers values(1349, "Pipeline");
INSERT into transformers values(1350, "Mudflap");
INSERT into transformers values(1351, "Flatbet");
INSERT into transformers values(1352, "Lander");
INSERT into transformers values(1353, "Kingbolt");
INSERT into transformers values(1354, "Red Hot");
INSERT into transformers values(1355, "Dead End ");
INSERT into transformers values(1356, "Macabre");
INSERT into transformers values(1357, "Gobots");
INSERT into transformers values(1358, "Skysickle ");
INSERT into transformers values(1359, "Warpath");
INSERT into transformers values(1360, "High Score 100");
INSERT into transformers values(1361, "Heinrad");
INSERT into transformers values(1362, "Wing");
INSERT into transformers values(1363, "Scourge");
INSERT into transformers values(1364, "Galvatron");
INSERT into transformers values(1365, "Tailspin");
INSERT into transformers values(1366, "Delta Seeker");
INSERT into transformers values(1367, "Black Zarak");
INSERT into transformers values(1368, "Crazybolt");
INSERT into transformers values(1369, "Crumplezone");
INSERT into transformers values(1370, "Screech");
INSERT into transformers values(1371, "Wedge");
INSERT into transformers values(1372, "Freeway");
INSERT into transformers values(1373, "Claw Jaw");
INSERT into transformers values(1374, "Onyx Primal");
INSERT into transformers values(1375, "Astroscope");
INSERT into transformers values(1376, "Vanishing");
INSERT into transformers values(1377, "Overhaul ");
INSERT into transformers values(1378, "Hound");
INSERT into transformers values(1379, "Railspike Major");
INSERT into transformers values(1380, "Fire");
INSERT into transformers values(1381, "Ruckus");
INSERT into transformers values(1382, "Gas Skunk");
INSERT into transformers values(1383, "Depthcharge");
INSERT into transformers values(1384, "Victory Saber");
INSERT into transformers values(1385, "Road Police");
INSERT into transformers values(1386, "Rotgut");
INSERT into transformers values(1387, "Rairyu");
INSERT into transformers values(1388, "Gasket");
INSERT into transformers values(1389, "Nosecone");
INSERT into transformers values(1390, "Whisper");
INSERT into transformers values(1391, "Rockbuster");
INSERT into transformers values(1392, "Metroshot");
INSERT into transformers values(1393, "Vector Prime");
INSERT into transformers values(1394, "Gideon");
INSERT into transformers values(1395, "Apache");
INSERT into transformers values(1396, "Ramulus");
INSERT into transformers values(1397, "Airlift");
INSERT into transformers values(1398, "Heavy Load");
INSERT into transformers values(1399, "Powered Convoy Magnus");
INSERT into transformers values(1400, "Grit");
INSERT into transformers values(1401, "Gimlet");
INSERT into transformers values(1402, "Dinoking");
INSERT into transformers values(1403, "Banzaitron");
INSERT into transformers values(1404, "Wreckage");
INSERT into transformers values(1405, "SteelBelt");
INSERT into transformers values(1406, "Rartorata");
INSERT into transformers values(1407, "Glitch");
INSERT into transformers values(1408, "Ratbat ");
INSERT into transformers values(1409, "AstroHook");
INSERT into transformers values(1410, "Mindset");
INSERT into transformers values(1411, "Blacker");
INSERT into transformers values(1412, "Dogfight");
INSERT into transformers values(1413, "Turtler");
INSERT into transformers values(1414, "Buckethead");
INSERT into transformers values(1415, "Motormaster");
INSERT into transformers values(1416, "Battletrap");
INSERT into transformers values(1417, "Power Punch");
INSERT into transformers values(1418, "Spinchange");
INSERT into transformers values(1419, "Jolt");
INSERT into transformers values(1420, "Prowl");
INSERT into transformers values(1421, "Switchblade");
INSERT into transformers values(1422, "Octus");
INSERT into transformers values(1423, "Deadwheeler");
INSERT into transformers values(1424, "Side Swipe");
INSERT into transformers values(1425, "Lightbright");
INSERT into transformers values(1426, "Big Hauler");
INSERT into transformers values(1427, "Triac");
INSERT into transformers values(1428, "Crasher");
INSERT into transformers values(1429, "Slow Poke");
